# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0002_auto_20170118_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='appreciators',
            field=models.ManyToManyField(related_name='appreciated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
